### ISSUE TITLE
Any Help for collector configuration

### ISSUE THREAD

**Issue by phavira168** [nordic-institute/X-Road-Metrics#109]
HI! 

i try to run xroad-metrics-collector collect, i got error. 
but i run xroad-metrics-collector list return correctly.

collector collect return 
<img width="1788" alt="Screenshot 2024-04-26 at 3 51 18 PM" src="https://github.com/nordic-institute/X-Road-Metrics/assets/142287300/0df1112b-a95d-40a1-9965-c1bafb5de6f4">

Collector Setting
<img width="1788" alt="Screenshot 2024-04-26 at 4 12 51 PM" src="https://github.com/nordic-institute/X-Road-Metrics/assets/142287300/3438c28a-3000-4ae7-9ec0-3ac846357907">

**Comment by raits** [comment]
Hey @phavira168! 

It looks like you have added the client certificates for the `security-server` block. Are you trying to set up mTLS authentication? If not you could try commenting out the certificate and key lines in the configuration.

**Comment by phavira168** [comment]
Hi @raits, 
i comment out configuration follow your suggestion already. but still error the same. 

<img width="1788" alt="Screenshot 2024-04-26 at 5 40 31 PM" src="https://github.com/nordic-institute/X-Road-Metrics/assets/142287300/c24e9b60-c13e-431b-919d-c6cab3b199c7">

**Comment by raits** [comment]
Ah, sorry, I misread the logs a bit earlier. It looks instead like the MongoDB configuration is incorrect since it seems that it is the `pymongo` library that is giving the error. Please check that the username and password are correct.

Since you have the MongoDB username set as `root`, I suspect that you have also not ran the database setup script to get the correct users, password and collections that should be used. Please follow the instructions [here](https://github.com/nordic-institute/X-Road-Metrics/blob/develop/docs/database_module.md#Indexes) and update your MongoDB credentials accordingly after that.
